<?php
$API = array(
    'authLogin'=>array(
        'methods'=>array(
            'cekResult'=>array(
                'len'=>1
            )
        )
    ),
    'QueryOrder'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            ),
            'getSummary'=>array(
                'len'=>1
            )

        )
    ),
    'QueryOrderfidusia'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            ),
            'getSummary'=>array(
                'len'=>1
            )

        )
    ),
    'QueryOrderdetail'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsU'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryOrderdetailfidusia'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsU'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryUser'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryLayanan'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryOfficer'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryOutsource'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryBank'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryKlien'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryKota'=>array(
        'methods'=>array(
            'getResultsId'=>array(
                'len'=>1
            )
        )
    ),
    'QueryPaket'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryPaketLayanan'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryDokumenLayanan'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    ),
    'QueryDokumenLayananfidusia'=>array(
        'methods'=>array(
            'getResults'=>array(
                'len'=>1
            ),
            'getResultsId'=>array(
                'len'=>1
            ),
            'createRecord'=>array(
                'len'=>1,
            ),
            'updateRecords'=>array(
                'len'=>1
            ),
            'destroyRecord'=>array(
                'len'=>1
            )
        )
    )

);
?>
